DROP IF EXISTS TABLE ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
    ID_ODONTOLOGO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    MATRICULA INTEGER NOT NULL,
);


